{% set name = "dpd_components" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dpd_components-{{ version }}.tar.gz
  sha256: 5db0f68abf2f8d3b0219876b6bac78eca1e311ae71062ea7531508f10f28f6b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - plotly
    - dash >=2.0
    - dash-bootstrap-components

test:
  imports:
    - dpd_components
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Django Plotly Dash component suite
  home: https://github.com/GibbsConsulting/dpd-components
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://dash.plotly.com/plugins
  dev_url: https://github.com/GibbsConsulting/dpd-components

extra:
  recipe-maintainers:
    - karthick1304
    - rxm7706
